### ISSUE TITLE
Is it possible to integrate is.js with angular?

### ISSUE THREAD

**Issue by michele-prandina** [scottrabin/is-js#14]
I wonder if is possibile to add it as a dependency eg: 
```javascript
angular.controller('Ctrl', ['$scope', '$isJs', function($scope, $isJs){
 if($scope.someModel.is.Something()) {
  doSomething; 
 }
}]);
```

**Comment by scottrabin** [comment]
That level of method chaining is certainly possible, but far outside the scope of this library. The only purpose this library has is correct determination of types in Javascript, which is sadly non-trivial. Integration with other libraries and frameworks is better suited to each of those packages, since each has a different way to integrate with their module system.

That said, I'm not exactly sure what `.is.Something()` is accomplishing here - can you not call `is.something($scope.someModel)`?
